apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-express-app
  template:
    metadata:
      labels:
        app: hello-world-express-app
    spec:
      containers:
      - name: hello-world-express
        image: your-dockerhub-username/hello-world-express:latest
        ports:
        - containerPort: 3000
